[project]
name = "py"
version = "0.1.0"
description = "python partition: nmodel export"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["onnx>=1.18.0", "onnxruntime>=1.22.1", "torch>=2.7.1"]

[tool.basedpyright]
typeCheckingMode = "basic"
